[package]
name = "kyano"
version = "0.1.0"
authors = ["Kyando_2 <amehikoji@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24.0"
vulkano = "0.22.0"
vulkano-win = "0.22.0"
